#!/usr/bin/env php
<?php

    use Doctrine\ORM\EntityManager;
    use Doctrine\ORM\Tools\Console\ConsoleRunner;
    use Doctrine\ORM\Tools\Console\EntityManagerProvider\SingleManagerProvider;
    use Slim\Container;

    require_once __DIR__ . '/vendor/autoload.php';

    $dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
    $dotenv->load();

    /** @var Container $container */
    $container = require_once __DIR__ . '/src/bootstrap.php';

    ConsoleRunner::run(
        new SingleManagerProvider($container->get(EntityManager::class))
    );